project(LoadLibraries)
include(${CMAKE_SOURCE_DIR}/cmake/utils/glew.cmake)
include(${CMAKE_SOURCE_DIR}/cmake/utils/GLFW.cmake)
include(${CMAKE_SOURCE_DIR}/cmake/utils/imgui.cmake)
include(${CMAKE_SOURCE_DIR}/cmake/utils/imnode.cmake)